name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Starting Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_DESCRIPTION=$(git log --pretty=format:"%s by %an (%D)" -n 1)
          curl -H "Content-Type: application/json" -X POST -d "{\"embeds\": [{\"title\": \"Building Mod\",\"color\": 3447003, \"description\": \"Building \`\`$COMMIT_DESCRIPTION\`\`\"}]}" $DISCORD_WEBHOOK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      - name: Build Success Notification
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
 - name: Discord notification 2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_DESCRIPTION=$(git log --pretty=format:"%s by %an (%D)" -n 1)
          curl -H "Content-Type: application/json" -X POST -d "{\"embeds\": [{\"title\": \"Build Successful\",\"color\": 3066993, \"description\": \"Successfully built \`\`$COMMIT_DESCRIPTION\`\`\"}]}" $DISCORD_WEBHOOK
